services:
  - type: web
    name: plant-disease-api
    env: docker
    plan: free # Change this to starter/standard depending on model size and traffic needs
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
